// <auto-generated />
using System;
using FinanzasApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanzasApp.Migrations
{
    [DbContext(typeof(FinanzasDbContext))]
    [Migration("20260307194347_CambioInversionesAhorros")]
    partial class CambioInversionesAhorros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FinanzasApp.Models.Accion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioActual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioPromedio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("FinanzasApp.Models.AhorroMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MetaObjetivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorActual")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ahorros");
                });

            modelBuilder.Entity("FinanzasApp.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaPadreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeObjetivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPadreId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Casa",
                            Orden = 0,
                            PorcentajeObjetivo = 0m,
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaPadreId = 1,
                            Nombre = "Arriendo",
                            Orden = 0,
                            PorcentajeObjetivo = 0m,
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaPadreId = 1,
                            Nombre = "Mercado",
                            Orden = 0,
                            PorcentajeObjetivo = 0m,
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaPadreId = 1,
                            Nombre = "Servicios",
                            Orden = 0,
                            PorcentajeObjetivo = 0m,
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Transporte",
                            Orden = 0,
                            PorcentajeObjetivo = 0m,
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaPadreId = 5,
                            Nombre = "Gasolina",
                            Orden = 0,
                            PorcentajeObjetivo = 0m,
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = 7,
                            CategoriaPadreId = 5,
                            Nombre = "Uber",
                            Orden = 0,
                            PorcentajeObjetivo = 0m,
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Deudas",
                            Orden = 0,
                            PorcentajeObjetivo = 0m,
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = 9,
                            CategoriaPadreId = 8,
                            Nombre = "Tarjeta Visa",
                            Orden = 0,
                            PorcentajeObjetivo = 0m,
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = 10,
                            CategoriaPadreId = 8,
                            Nombre = "Credito carro",
                            Orden = 0,
                            PorcentajeObjetivo = 0m,
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Ahorro",
                            Orden = 0,
                            PorcentajeObjetivo = 0m,
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = 12,
                            CategoriaPadreId = 11,
                            Nombre = "Fondo emergencia",
                            Orden = 0,
                            PorcentajeObjetivo = 0m,
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id = 13,
                            CategoriaPadreId = 11,
                            Nombre = "Inversion",
                            Orden = 0,
                            PorcentajeObjetivo = 0m,
                            Tipo = "Gasto"
                        });
                });

            modelBuilder.Entity("FinanzasApp.Models.ConfiguracionFinanciera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IngresoBaseMensual")
                        .HasColumnType("TEXT");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcAhorroInversion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcCasaFijosMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcCasaFijosMin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcDeudaMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcDeudaMin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcDiversionMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcOtrosMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcTransporteMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcTransporteMin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UmbralAmarillo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UmbralRojo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configuraciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngresoBaseMensual = 0m,
                            Moneda = "COP",
                            PorcAhorroInversion = 7m,
                            PorcCasaFijosMax = 28m,
                            PorcCasaFijosMin = 23m,
                            PorcDeudaMax = 22m,
                            PorcDeudaMin = 18m,
                            PorcDiversionMax = 3m,
                            PorcOtrosMax = 8m,
                            PorcTransporteMax = 5m,
                            PorcTransporteMin = 4m,
                            UmbralAmarillo = 95m,
                            UmbralRojo = 105m
                        });
                });

            modelBuilder.Entity("FinanzasApp.Models.Deuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PagoMinimo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PagoObjetivo")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrioridadManual")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SaldoActual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTasa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Deudas");
                });

            modelBuilder.Entity("FinanzasApp.Models.FondoEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AporteMensual")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorActual")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FondosEmpleado");
                });

            modelBuilder.Entity("FinanzasApp.Models.Inversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AportesAcumulados")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CapitalInicial")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TasaEA")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inversiones");
                });

            modelBuilder.Entity("FinanzasApp.Models.MesFinanciero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaCerrado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ingreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("MesKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MesKey")
                        .IsUnique();

                    b.ToTable("MesesFinancieros");
                });

            modelBuilder.Entity("FinanzasApp.Models.PresupuestoCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MesFinancieroId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Real")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MesFinancieroId");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("FinanzasApp.Models.Categoria", b =>
                {
                    b.HasOne("FinanzasApp.Models.Categoria", "CategoriaPadre")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaPadre");
                });

            modelBuilder.Entity("FinanzasApp.Models.PresupuestoCategoria", b =>
                {
                    b.HasOne("FinanzasApp.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanzasApp.Models.MesFinanciero", "Mes")
                        .WithMany("Presupuestos")
                        .HasForeignKey("MesFinancieroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Mes");
                });

            modelBuilder.Entity("FinanzasApp.Models.Categoria", b =>
                {
                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("FinanzasApp.Models.MesFinanciero", b =>
                {
                    b.Navigation("Presupuestos");
                });
#pragma warning restore 612, 618
        }
    }
}
