// <auto-generated />
using System;
using FinanzasApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanzasApp.Migrations
{
    [DbContext(typeof(FinanzasDbContext))]
    [Migration("20260306233428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FinanzasApp.Models.Deuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PagoMinimo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PagoObjetivo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridad")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TasaEA")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Deudas");
                });

            modelBuilder.Entity("FinanzasApp.Models.Inversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CapitalInicial")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TasaEA")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inversiones");
                });

            modelBuilder.Entity("FinanzasApp.Models.MesFinanciero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ingreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Patrimonio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAhorro")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDeuda")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalGastos")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Meses");
                });
#pragma warning restore 612, 618
        }
    }
}
