// <auto-generated />
using System;
using FinanzasApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanzasApp.Migrations
{
    [DbContext(typeof(FinanzasDbContext))]
    [Migration("20260307024201_UpdateInversion")]
    partial class UpdateInversion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FinanzasApp.Models.Accion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioActual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioPromedio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("FinanzasApp.Models.AhorroMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MetaObjetivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorActual")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ahorros");
                });

            modelBuilder.Entity("FinanzasApp.Models.ConfiguracionFinanciera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IngresoBaseMensual")
                        .HasColumnType("TEXT");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcAhorroInversion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcCasaFijosMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcCasaFijosMin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcDeudaMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcDeudaMin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcDiversionMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcOtrosMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcTransporteMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcTransporteMin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UmbralAmarillo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UmbralRojo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configuraciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngresoBaseMensual = 0m,
                            Moneda = "COP",
                            PorcAhorroInversion = 7m,
                            PorcCasaFijosMax = 28m,
                            PorcCasaFijosMin = 23m,
                            PorcDeudaMax = 22m,
                            PorcDeudaMin = 18m,
                            PorcDiversionMax = 3m,
                            PorcOtrosMax = 8m,
                            PorcTransporteMax = 5m,
                            PorcTransporteMin = 4m,
                            UmbralAmarillo = 95m,
                            UmbralRojo = 105m
                        });
                });

            modelBuilder.Entity("FinanzasApp.Models.Deuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PagoMinimo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PagoObjetivo")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrioridadManual")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SaldoActual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTasa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Deudas");
                });

            modelBuilder.Entity("FinanzasApp.Models.FondoEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AporteMensual")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorActual")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FondosEmpleado");
                });

            modelBuilder.Entity("FinanzasApp.Models.Inversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AportesAcumulados")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CapitalInicial")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TasaEA")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inversiones");
                });

            modelBuilder.Entity("FinanzasApp.Models.MesFinanciero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AhorroInversionPresupuesto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AhorroInversionReal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CasaFijosPresupuesto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CasaFijosReal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeudaPresupuesto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeudaReal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiversionPresupuesto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiversionReal")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaCerrado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ingreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("MesKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OtrosPresupuesto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OtrosReal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TransportePresupuesto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TransporteReal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MesKey")
                        .IsUnique();

                    b.ToTable("Meses");
                });
#pragma warning restore 612, 618
        }
    }
}
